### ISSUE TITLE
Вычитка руководства миграции на PHP 7.4 

### ISSUE THREAD

**Issue by lex111** [php-ru/php-doc-ru#3]
Привет @saundefined, было бы здорово, если ты посмотрел первоначальный перевод миграции на PHP 7.4
http://svn.php.net/viewvc/phpdoc/ru/trunk/appendices/migration74/

**Comment by saundefined** [comment]
Привет, сегодня гляну

**Comment by lex111** [comment]
Вижу исправления, спасибо!

Единственное, всё равно не понимаю употребление в/на в сочетании с вызовами функции, т.е.

Вызов ... на объекте -> вызов ... в объекте

И тут понял, что это тоже неверно и непонятно, тогда лучше всего будет так:

Вызов ... с объектом

Как такой вариант?

**Comment by saundefined** [comment]
Хм.. да, думаю, "с объектом" корректнее будет 🤔

**Comment by saundefined** [comment]
Подготовил правки, если оставляем этот вариант - закоммичу

в объектах => с объектом
[R93](https://github.com/php-ru/php-doc-ru/commit/cf25bb0194e604e5156ee8dcc32e57aecd1883a6#diff-054696e41d31f2dcaf72d5d3105f93deR93), [R96](https://github.com/php-ru/php-doc-ru/commit/cf25bb0194e604e5156ee8dcc32e57aecd1883a6#diff-054696e41d31f2dcaf72d5d3105f93deR96)

в потоке => с потоком
[R59](https://github.com/php-ru/php-doc-ru/commit/cf25bb0194e604e5156ee8dcc32e57aecd1883a6#diff-c8eec03a8ccc53578a774a429249a123R59)

в/на экземпляре => с экземпляром
[R259](https://github.com/php-ru/php-doc-ru/commit/cf25bb0194e604e5156ee8dcc32e57aecd1883a6#diff-c8eec03a8ccc53578a774a429249a123R259), [L175](https://github.com/php-ru/php-doc-ru/blob/cf25bb0194e604e5156ee8dcc32e57aecd1883a6/appendices/migration74/incompatible.xml#L175)

в свойствах => со свойствами
[R281](https://github.com/php-ru/php-doc-ru/commit/cf25bb0194e604e5156ee8dcc32e57aecd1883a6#diff-c8eec03a8ccc53578a774a429249a123R281)

**Comment by lex111** [comment]
Да, давай.
